name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      # Step 3: Build the JAR file using Maven (skip tests)
      - name: Build JAR file
        run: |
          chmod +x mvnw && ./mvnw clean package -DskipTests

      # Step 4: Generate timestamp-based tag (yyyyMMddHHmm)
      - name: Generate timestamp-based tag
        id: timestamp
        run: echo "TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      # Step 5: Build Docker Image using the built JAR file
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/rental-backend:${{ env.TAG }} -t ghcr.io/${{ github.repository }}/rental-backend:latest .

      # Step 6: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Push Docker Image to GitHub Container Registry
      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/rental-backend:${{ env.TAG }}
          docker push ghcr.io/${{ github.repository }}/rental-backend:latest